# Generated by Django 4.2.4 on 2023-08-30 10:46

from django.db import migrations

import kit.models


class Migration(migrations.Migration):
    dependencies = [
        ("kit", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", kit.models.KitUserManager()),
            ],
        ),
    ]
