# Generated by Django 4.2.4 on 2023-08-24 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import kit.validators
import userprofile.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(verbose_name="Bio")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=userprofile.models.generate_uuid_for_author_avatar,
                        validators=[
                            kit.validators.FileSizeValidator(1048576),
                            kit.validators.FileExtensionValidator([".png", ".jpeg", ".jpg"]),
                        ],
                        verbose_name="Avatar",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
